/**
 * Extracts the first page's text from a PDF, reconstructed into reading-order lines.
 * pdf.js reports text items in content-stream order (not visual order), which garbles
 * RTL text if you just concatenate items — so instead we group items by y-position into
 * lines, then sort each line right-to-left by x-position.
 *
 * The pdfjs-dist import is dynamic (not a top-level import) so this module never loads
 * that dependency unless extraction actually runs — kept out of any shared bundle.
 */
async function extractFirstPageLines(buffer: Buffer): Promise<string[]> {
  const { getDocument } = await import("pdfjs-dist/legacy/build/pdf.mjs");

  const data = new Uint8Array(buffer);
  const doc = await getDocument({ data, useWorkerFetch: false, isEvalSupported: false }).promise;
  const page = await doc.getPage(1);
  const content = await page.getTextContent();

  const lines = new Map<number, Array<{ str: string; x: number }>>();
  for (const item of content.items as Array<{ str: string; transform: number[] }>) {
    const y = Math.round(item.transform[5]);
    if (!lines.has(y)) lines.set(y, []);
    lines.get(y)!.push({ str: item.str, x: item.transform[4] });
  }

  const sortedYs = [...lines.keys()].sort((a, b) => b - a);
  return sortedYs.map((y) =>
    lines
      .get(y)!
      .sort((a, b) => b.x - a.x)
      .map((i) => i.str)
      .join("")
  );
}

/**
 * Pulls the equipment list out of a lesson-plan PDF generated by our "חיים בתנועה"
 * template, where it's always labelled "ציוד:" on its own line(s), right before the
 * next labelled field (e.g. "לפני השיעור:"). Returns a newline-joined string of
 * "<quantity> <name>" entries (ready for the equipment textarea), or null if the
 * label wasn't found.
 */
export async function extractEquipmentTextFromPdf(buffer: Buffer): Promise<string | null> {
  const lines = await extractFirstPageLines(buffer);

  const startIndex = lines.findIndex((line) => line.includes("ציוד:"));
  if (startIndex === -1) return null;

  const parts: string[] = [];
  const firstLine = lines[startIndex].replace(/ציוד:/g, "").trim();
  if (firstLine) parts.push(firstLine);

  for (let i = startIndex + 1; i < lines.length; i++) {
    if (lines[i].includes(":")) break;
    const line = lines[i].trim();
    if (line) parts.push(line);
  }

  const joined = parts.join(" ").trim();
  if (!joined) return null;

  return joined
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .join("\n");
}
